name: Deploy and Check Balance

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 12 * * *'  # Ежедневная проверка в 12:00 UTC

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to Render
        uses: render-actions/deploy@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
          serviceId: srv-d0vflq7fte5s739klnr0
          envVars: |
            TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
            DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
  
  check_balance:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Check DeepSeek Balance
        run: |
          pip install openai
          python -c "
          import os
          from openai import OpenAI
          
          api_key = os.getenv('DEEPSEEK_API_KEY')
          if not api_key:
              print('API key not set!')
              exit(1)
              
          client = OpenAI(api_key=api_key, base_url='https://api.deepseek.com/v1')
          
          try:
              # Попробуйте получить информацию о балансе
              usage = client.usage.list(limit=1)
              if usage.data[0].balance <= 0.1:
                  print('⚠️ ВНИМАНИЕ: Баланс DeepSeek ниже $0.1!')
                  # Здесь можно добавить отправку уведомления
              else:
                  print(f'Текущий баланс: ${usage.data[0].balance}')
          except Exception as e:
              print(f'Ошибка при проверке баланса: {str(e)}')
          "
        env:
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
